### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Shankar-MMV** [visves/BoomHwyl_Startup#1]
To be completed within 16th Jan

**Comment by visves** [comment]
16th ???? ok take your own time.. but need best Logo

**Comment by Shankar-MMV** [comment]
@visves can you give a look-alike/theme for logo design(you told earlier but forget), so that i could work with!! if we go for online logo makers we get simple icons as below
![1](https://cloud.githubusercontent.com/assets/25059061/21867340/c49c35da-d873-11e6-90a2-1a8b70d6a39b.png)
![index](https://cloud.githubusercontent.com/assets/25059061/21867341/c49d1e5a-d873-11e6-8dfc-89a8b43df3e0.png)
![zjhl2lgef9cyrql0jfa7kzbw2vucrrbhkb3i3jd9oxde9g5shnn1i bv9ettdv9dsbugw0py](https://cloud.githubusercontent.com/assets/25059061/21867339/c49b0250-d873-11e6-9ece-97f25985a153.png)
![zjhl2lgef9cyrql0jfa7kzbw2vucrrbhkbrl1zp9oxde9g5shnn1i bv9ettdv9dsbugw0py](https://cloud.githubusercontent.com/assets/25059061/21867342/c4a04fbc-d873-11e6-8c78-a2b226cbb418.png)

@ramji1212  suggestions please

**Comment by visves** [comment]
Try something like this 
![image](https://cloud.githubusercontent.com/assets/17913243/21883355/b52ebb84-d8d4-11e6-998d-ccdc9a702599.png)

**Comment by visves** [comment]
try like connecting logo / Icon . This is the theme we were working on.. Connecting companies that is our ERP Tool's main moto
![image](https://cloud.githubusercontent.com/assets/17913243/21883397/ead68b40-d8d4-11e6-9d48-755285937522.png)


and not limited to this.. for example: amazon , sony vaio logo.. hidden meaning is better.. 
you can use BH in the logo thats no problem, if not also ok..

**Comment by Shankar-MMV** [comment]
![bh1](https://cloud.githubusercontent.com/assets/25059061/22145262/9db50a82-df26-11e6-9b63-3825c733c18d.PNG)
![bh2](https://cloud.githubusercontent.com/assets/25059061/22145263/9db9e02a-df26-11e6-8f2c-1f12a580d7b4.PNG)
![bh3](https://cloud.githubusercontent.com/assets/25059061/22145266/9dc5126a-df26-11e6-9a20-9da7678cb9f7.PNG)
![bh4](https://cloud.githubusercontent.com/assets/25059061/22145264/9dbc6d9a-df26-11e6-9dbb-dc2e14c18299.PNG)
![bh5](https://cloud.githubusercontent.com/assets/25059061/22145267/9dc7341e-df26-11e6-8bc6-fe3586c0ec9f.PNG)
![bh6](https://cloud.githubusercontent.com/assets/25059061/22145268/9dd0b37c-df26-11e6-9fed-65772b8eaf6c.PNG)
![bh7](https://cloud.githubusercontent.com/assets/25059061/22145269/9de38e98-df26-11e6-9c49-cffc3c26c2b0.PNG)
![bh8](https://cloud.githubusercontent.com/assets/25059061/22145272/9df766f2-df26-11e6-918a-117258637862.PNG)
![bh9](https://cloud.githubusercontent.com/assets/25059061/22145270/9df14d1c-df26-11e6-81fd-635457c64c63.PNG)
![bh10](https://cloud.githubusercontent.com/assets/25059061/22145271/9df41100-df26-11e6-90b1-12ac6feaecd2.PNG)
![bh11](https://cloud.githubusercontent.com/assets/25059061/22145273/9dfa8db4-df26-11e6-9ede-13e5a914d432.PNG)
![bh12](https://cloud.githubusercontent.com/assets/25059061/22145274/9dfe5714-df26-11e6-8fc7-1ad471cd8619.PNG)
![bh13](https://cloud.githubusercontent.com/assets/25059061/22145275/9e0bde70-df26-11e6-856b-19bec361c24c.PNG)
![bh14](https://cloud.githubusercontent.com/assets/25059061/22145277/9e2a05ee-df26-11e6-8f4b-ee3d3c82f05d.PNG)
![bh15](https://cloud.githubusercontent.com/assets/25059061/22145276/9e29f400-df26-11e6-9ced-303bfa94c193.PNG)
![bh16](https://cloud.githubusercontent.com/assets/25059061/22145280/9e303234-df26-11e6-9286-f94bc50bcbe3.PNG)
![bh17](https://cloud.githubusercontent.com/assets/25059061/22145278/9e2af940-df26-11e6-8f81-8b637f9864d8.PNG)
![bh18](https://cloud.githubusercontent.com/assets/25059061/22145279/9e2b31f8-df26-11e6-828a-3c451172537b.PNG)
![bh19](https://cloud.githubusercontent.com/assets/25059061/22145281/9e4040ac-df26-11e6-86b6-e118d8c355b1.PNG)
![bh20](https://cloud.githubusercontent.com/assets/25059061/22145282/9e63ea52-df26-11e6-9f1a-d07945bf7317.PNG)
![bh21](https://cloud.githubusercontent.com/assets/25059061/22145283/9e63ee76-df26-11e6-99d6-c8054d52e45e.PNG)
![bh22](https://cloud.githubusercontent.com/assets/25059061/22145284/9e65ad92-df26-11e6-985d-d8df0cd6be00.PNG)
![bh23](https://cloud.githubusercontent.com/assets/25059061/22145285/9e7323c8-df26-11e6-8fd6-8962d1038874.PNG)
![bh24](https://cloud.githubusercontent.com/assets/25059061/22145287/9e777c3e-df26-11e6-81b8-e0ee61881957.PNG)
![bh25](https://cloud.githubusercontent.com/assets/25059061/22145288/9e7a9d10-df26-11e6-84d2-01822688d443.PNG)

**Comment by Shankar-MMV** [comment]
@visves @ramji1212 
25 logos are here, it will be simple (also bad), if so suggests for modifications, Thanks!

**Comment by visves** [comment]
Good start... !!!

Name use panama logo panu da... like i send you previously...
13th logo nala iruku 
but athula steps pora mari iruntha nala irukum,konjam edit pani paru atha
18th logo um konjam alter pani paru something meaning 
@Shankar-MMV

**Comment by visves** [comment]
Hi guys, 
check the below Logos
need your suggestions...
![image](https://cloud.githubusercontent.com/assets/17913243/22175705/56866aca-e020-11e6-9738-af52926ca3ec.png)
![image](https://cloud.githubusercontent.com/assets/17913243/22175706/5e70ce10-e020-11e6-99fc-f81128a583e0.png)
![image](https://cloud.githubusercontent.com/assets/17913243/22175708/620298a6-e020-11e6-9b92-fa8746309a94.png)
![image](https://cloud.githubusercontent.com/assets/17913243/22175709/641cf000-e020-11e6-961d-f3e8112e7411.png)
![image](https://cloud.githubusercontent.com/assets/17913243/22175710/662eacb2-e020-11e6-830c-ef06bcba5ce5.png)
![image](https://cloud.githubusercontent.com/assets/17913243/22175711/67dfa85e-e020-11e6-9474-ccbdfde4d8e7.png)
ithula name ilama vachukalam....

**Comment by visves** [comment]
Check this logo also

![image](https://cloud.githubusercontent.com/assets/17913243/22263942/311a8a9a-e29c-11e6-93f9-82ef48a7f87a.png)

![9cd70ba2-ee0b-40b1-a1a1-624c78435923](https://cloud.githubusercontent.com/assets/17913243/22263890/005aa44e-e29c-11e6-8d92-22147efc22ce.png)
![0da3784a-63c0-43d8-becb-9143d4b41102](https://cloud.githubusercontent.com/assets/17913243/22263891/007ea3c6-e29c-11e6-8558-20dec4f3d928.png)
![4c9944f4-c8ca-48ca-88a6-f12a81d615a4](https://cloud.githubusercontent.com/assets/17913243/22263892/0086a062-e29c-11e6-80c7-c39581f64bdc.png)

**Comment by Shankar-MMV** [comment]
sema da
looking good

**Comment by Shankar-MMV** [comment]
![bh1](https://cloud.githubusercontent.com/assets/25059061/22264172/106792f6-e29d-11e6-94c2-0ebfadd94f13.png)
![bh11](https://cloud.githubusercontent.com/assets/25059061/22264175/106a3c2c-e29d-11e6-8fcc-f36b833ee0ee.png)
![bh](https://cloud.githubusercontent.com/assets/25059061/22264177/1076b89e-e29d-11e6-8d8e-d80dbf4abfaf.png)
![bh3](https://cloud.githubusercontent.com/assets/25059061/22264176/106b3dac-e29d-11e6-97d7-5f92dd33cd33.png)
![bh5](https://cloud.githubusercontent.com/assets/25059061/22264174/1069f08c-e29d-11e6-9c08-906d8e8ff212.png)
![bha](https://cloud.githubusercontent.com/assets/25059061/22264173/106946dc-e29d-11e6-93dc-924cec16b1c3.png)
![bhb](https://cloud.githubusercontent.com/assets/25059061/22264182/109a0fc4-e29d-11e6-9c95-ec956780d66d.png)
![bhj](https://cloud.githubusercontent.com/assets/25059061/22264180/109827b8-e29d-11e6-892f-e1464e61b696.png)
![bhjjjj](https://cloud.githubusercontent.com/assets/25059061/22264184/109bdd36-e29d-11e6-9ef7-07edc6300c85.png)
![bhm](https://cloud.githubusercontent.com/assets/25059061/22264183/109b799a-e29d-11e6-9387-cf1ca00a0b53.png)
![bhmm](https://cloud.githubusercontent.com/assets/25059061/22264178/109758ce-e29d-11e6-9978-ea0b7e06f7e6.png)
![bhmmm](https://cloud.githubusercontent.com/assets/25059061/22264181/1098d7e4-e29d-11e6-9f00-2ecf0b7e873f.png)
![bhr](https://cloud.githubusercontent.com/assets/25059061/22264179/10979cda-e29d-11e6-8264-9537002e93f1.png)
![bht](https://cloud.githubusercontent.com/assets/25059061/22264185/109e5bec-e29d-11e6-915a-fff17dcff000.png)

**Comment by Shankar-MMV** [comment]
@visves  ne comment panadula 2,3,4 good
@ramji1212 ne solu da

**Comment by visves** [comment]
Network B is good and inspire logo also good 
we have to decide from this two logo... 
2nd logo image is ok but the background has to be changed...
try this B logo in both white with black background and black with white background 
@Shankar-MMV

**Comment by Shankar-MMV** [comment]
![d](https://cloud.githubusercontent.com/assets/25059061/22334131/8d3357a8-e3ff-11e6-916d-48a3abfa7e83.PNG)
![d3](https://cloud.githubusercontent.com/assets/25059061/22334132/8d3475b6-e3ff-11e6-8ba3-8ed323ca85fa.PNG)
![d1](https://cloud.githubusercontent.com/assets/25059061/22334133/8d36b826-e3ff-11e6-8a54-2e7b6450c7f5.PNG)

**Comment by visves** [comment]
Finally Logo fixed... these are the below Logo which @Shankar-MMV made as best...
![boomhwyl b](https://cloud.githubusercontent.com/assets/17913243/22338391/40d61e78-e40d-11e6-9c6b-c0f0d06a842e.png)
![boomhwyl](https://cloud.githubusercontent.com/assets/17913243/22338392/40e38086-e40d-11e6-8167-39a9894933c0.png)
